player_classes = {
	1: "Warrior",
	2: "Paladin",
	3: "Hunter",
	4: "Rogue",
	5: "Priest",
	6: "Death Knight",
	7: "Shaman",
	8: "Mage",
	9: "Warlock",
	# 10 unused
	11: "Druid",
}

player_races = {
	1: "Human",
	2: "Orc",
	3: "Dwarf",
	4: "Night Elf",
	5: "Undead",
	6: "Tauren",
	7: "Gnome",
	8: "Troll",
	9: "Goblin",
	10: "Blood Elf",
	11: "Draenei",
}

genders = ("Male", "Female")

languages = {
	0: "Universal",
	1: "Orcish",
	2: "Darnassian",
	3: "Taurahe",
	6: "Dwarven",
	7: "Common",
	10: "Thalassian",
	13: "Gnomish",
	14: "Troll",
	33: "Gutterspeak",
	35: "Draenei",
	0xFFFFFFFF: "Addon",
}

message_types = {
	0xFFFFFFFF: "Addon",
	0x00: "System",
	0x01: "Say",
	0x02: "Party",
	0x03: "Raid",
	0x04: "Guild",
	0x05: "Officer",
	0x06: "Yell",
	0x07: "Whisper",
	0x08: "Whisper Information",
	0x09: "Reply",
	0x0A: "Emote",
	0x0B: "Text Emote",
	0x0C: "Monster Say",
	0x0D: "Monster Party",
	0x0E: "Monster Yell",
	0x0F: "Monster Whisper",
	0x10: "Monster Emote",
	0x11: "Channel",
	0x12: "Channel Join",
	0x13: "Channel Leave",
	0x14: "Channel List",
	0x15: "Channel Notice",
	0x16: "Channel Notice User",
	0x17: "AFK",
	0x18: "DND",
	0x19: "Ignored",
	0x1A: "Skill",
	0x1B: "Loot",
	0x1C: "Money",
	0x1D: "Opening",
	0x1E: "Tradeskills",
	0x1F: "Pet Info",
	0x20: "Combat Misc Info",
	0x21: "Combat XP Gain",
	0x22: "Combat Honor Gain",
	0x23: "Combat Faction Change",
	0x24: "Battleground System Neutral",
	0x25: "Battleground System Alliance",
	0x26: "Battleground System Horde",
	0x27: "Raid Leader",
	0x28: "Raid Warning",
	0x29: "Raid Boss Whisper",
	0x2A: "Raid Boss Emote",
	0x2B: "Filtered",
	0x2C: "Battleground",
	0x2D: "Battleground Leader",
	0x2E: "Restricted",
}
